# Starter pipeline
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      # Write your PowerShell commands here.
      
      Add-Type -AssemblyName System.speech
      Write-Host "#######################################"
      Write-Host "#     .___________________________.   #"
      Write-Host "#     | Hello, I am a Test Script |   #"
      Write-Host "#     | to be used for testing    |   #"
      Write-Host "#     | deployment pipelines!     |   #"
      Write-Host "#     '---------------------------'   #"
      Write-Host "#          ^       (\_/)              #"
      Write-Host "#          |_______(0.o)              #"
      Write-Host "#                  (> <)              #"
      Write-Host "#######################################"
      $tts= New-Object System.Speech.Synthesis.SpeechSynthesizer
      $tts.Speak('Hello, I am a Test Script to be used for testing deployment pipelines.')
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
